# Generated by Django 2.1.4 on 2018-12-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20181219_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('a1', models.CharField(blank=True, default='', max_length=100)),
                ('a2', models.CharField(blank=True, default='', max_length=100)),
                ('a3', models.CharField(blank=True, default='', max_length=100)),
                ('a4', models.CharField(blank=True, default='', max_length=100)),
                ('a5', models.CharField(blank=True, default='', max_length=100)),
                ('a6', models.CharField(blank=True, default='', max_length=100)),
                ('a7', models.CharField(blank=True, default='', max_length=100)),
                ('a8', models.CharField(blank=True, default='', max_length=100)),
                ('a9', models.CharField(blank=True, default='', max_length=100)),
                ('a10', models.CharField(blank=True, default='', max_length=100)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('m1', models.CharField(blank=True, default='', max_length=100)),
                ('m2', models.CharField(blank=True, default='', max_length=100)),
                ('m3', models.CharField(blank=True, default='', max_length=100)),
                ('m4', models.CharField(blank=True, default='', max_length=100)),
                ('m5', models.CharField(blank=True, default='', max_length=100)),
                ('m6', models.CharField(blank=True, default='', max_length=100)),
                ('m7', models.CharField(blank=True, default='', max_length=100)),
                ('m8', models.CharField(blank=True, default='', max_length=100)),
                ('m9', models.CharField(blank=True, default='', max_length=100)),
                ('m10', models.CharField(blank=True, default='', max_length=100)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('modelPath', models.CharField(default='', max_length=250)),
                ('result', models.CharField(blank=True, default='', max_length=100)),
                ('r1', models.CharField(blank=True, default='', max_length=100)),
                ('r2', models.CharField(blank=True, default='', max_length=100)),
                ('r3', models.CharField(blank=True, default='', max_length=100)),
                ('r4', models.CharField(blank=True, default='', max_length=100)),
                ('r5', models.CharField(blank=True, default='', max_length=100)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Algorithm')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='outstanding',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totals',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totalsAssets',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modela',
            name='stockData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.StockData'),
        ),
    ]
