# Generated by Django 2.1.4 on 2019-01-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20181220_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default='', max_length=100)),
                ('m1', models.CharField(blank=True, default='', max_length=100)),
                ('m2', models.CharField(blank=True, default='', max_length=100)),
                ('m3', models.CharField(blank=True, default='', max_length=100)),
                ('m4', models.CharField(blank=True, default='', max_length=100)),
                ('m5', models.CharField(blank=True, default='', max_length=100)),
                ('result', models.CharField(blank=True, default='', max_length=100)),
                ('dataStr', models.TextField(default='')),
                ('result1', models.CharField(blank=True, default='', max_length=100)),
                ('result2', models.CharField(blank=True, default='', max_length=100)),
                ('result3', models.CharField(blank=True, default='', max_length=100)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='StockCWData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('quarter', models.CharField(default='', max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('dimension', models.IntegerField(blank=True, null=True)),
                ('filePath', models.CharField(default='', max_length=250)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('startDate', models.TextField(default='')),
                ('endDate', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('algorithm', models.CharField(default='', max_length=100)),
                ('modelPath', models.CharField(default='', max_length=250)),
                ('evaResult', models.CharField(blank=True, default='', max_length=100)),
                ('dataNote', models.TextField(default='')),
                ('inputNote', models.TextField(default='')),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='StrategyPre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default='', max_length=100)),
                ('result', models.CharField(blank=True, default='', max_length=100)),
                ('result1', models.CharField(blank=True, default='', max_length=100)),
                ('result2', models.CharField(blank=True, default='', max_length=100)),
                ('result3', models.CharField(blank=True, default='', max_length=100)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Strategy')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TechnicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('technicalDatas', models.TextField(default='')),
                ('dimension', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('filePath', models.CharField(default='', max_length=250)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
                ('stockData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.StockData')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='modela',
            name='r1',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='modela',
            name='r2',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='modela',
            name='r3',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='modela',
            name='r4',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='modela',
            name='r5',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='modelpre',
            name='modelA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.ModelA'),
        ),
    ]
