# Generated by Django 2.1.4 on 2019-01-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20190104_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('nickname', models.CharField(default='', max_length=100)),
                ('tType', models.CharField(default='均线型', max_length=100)),
                ('interface', models.CharField(default='', max_length=100)),
                ('parameter1', models.CharField(default='', max_length=100)),
                ('parameter2', models.CharField(default='', max_length=100)),
                ('parameter3', models.CharField(default='', max_length=100)),
                ('parameter4', models.CharField(default='', max_length=100)),
                ('parameter5', models.CharField(default='', max_length=100)),
                ('isExpired', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
